### ISSUE TITLE
Error message from nextaction.py

### ISSUE THREAD

**Issue by larsito** [nikdoof/NextAction#8]
Hi and thanks for providing what seems to be a really helpful tool for todoist. I have managed as far as installing everything required and running nextaction.py with my personal API (having unzipped the zip file on my desktop, on MacOS 10.10). Then, however, I get the following error message. I am not familiar with python. Any suggestion if I am doing something basic wrong, or if it is a more general problem?

`Traceback (most recent call last):
  File "nextaction.py", line 184, in <module>
    main()
  File "nextaction.py", line 69, in main
    api.sync(resource_types=['projects', 'labels', 'items'])
TypeError: sync() got an unexpected keyword argument 'resource_types'
`

**Comment by nikdoof** [comment]
Use the `development` branch instead of `master`, recent changes to the API means that newer version of the todoist supplied python libraries do not allow selective syncing as used in the older version of NextAction.

You can grab the zip from [here](https://github.com/nikdoof/NextAction/archive/development.zip)
